### ISSUE TITLE
Error: cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by nickbe** [shuckster/iTunes-XML-parser-for-PHP#2]
This happens with PHP 7.3. Any idea what is wrong here?
Using the standard demo example with a standard iTunes xml.

**Comment by shuckster** [comment]
Thanks for the report @nickbe . I found a bug in the `sort()` accessors and committed a fix. Can you try again please?

**Comment by shuckster** [comment]
Will close this for now. Hope you've had some luck. If not, holla back. 👍

**Comment by nickbe** [comment]
I'll try that and report back. Thanks for investigating Shuckster !!!
