### ISSUE TITLE
Check attributions

### ISSUE THREAD

**Issue by shuckster** [shuckster/iTunes-XML-parser-for-PHP#4]
Just a note to ask @pietropizzi if he's the Peter Minarik I mention in the README.md.

(Creating this issue just to see if the @ symbol works to alert users to mentions... 🤔 )

**Comment by pietropizzi** [comment]
This is funny. I have no recollection of working on this at all? But now of course I'm interested. Do you remember where the contribution came from?

If you want you could update the website from wirsindecht.org to peterminarik.com 😊

**Comment by pietropizzi** [comment]
And also only seeing it now that you're closing this.

**Comment by robert-wallis** [comment]
In 2005 Peter Minarik with the username "oo73venty" emailed me a contribution.

The email subject line was "Re: [CodeTriangle.com] itunes_xml_parser" if that helps you find it in your email.

**Comment by pietropizzi** [comment]
Thanks. Haha emailing code contributions. Different times for sure 😊 could not find it, but slowly it is coming back to me

**Comment by shuckster** [comment]
Hey, thanks for dropping by! Interesting that the notification only worked on close. Links in the README all updated, thank you.

Hope the trip down memory lane has been a pleasant one. :)

**Comment by shuckster** [comment]
@pietropizzi - There's still a link to your old web-site in the [source](https://github.com/shuckster/iTunes-XML-parser-for-PHP/blob/master/iTunesXMLparser.class.php#L12).

I was going to fix it, but thought it might be nice if you were on the list of contributors that Github automatically generates.

If you're happy to make a PR to [update the line](https://github.com/shuckster/iTunes-XML-parser-for-PHP/blob/master/iTunesXMLparser.class.php#L12) go ahead.

**Comment by pietropizzi** [comment]
Thanks: https://github.com/shuckster/iTunes-XML-parser-for-PHP/pull/5
